# Source global definitions
if [ -f /etc/skell/.bashrc ]; then
. /etc/skell/bashrc
fi
# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=
# User specific aliases and functions
export PATH=$PATH:/usr/local/bin
# User specific aliases and functions
cowsay 'Hi this is Keerthi's puppet vm!'
